name: publish

on:
  workflow_call:
    inputs:
      project-name:
        description: The name of the project
        required: true
        type: string
      bun-version:
        description: The version of Bun to use (default `latest`)
        required: false
        default: latest
        type: string
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      with-submodules:
        description: Whether to include submodules when checking out the repository (default `false`)
        required: false
        default: 'false'
        type: string
      working-directory:
        description: The working directory to run the commands in
        required: false
        default: .
        type: string
      skip-automatic-bump:
        description: Whether to skip the automatic bumping of the package version
        required: false
        default: false
        type: boolean
      build:
        description: Whether to run `bun build` before publishing
        required: false
        default: false
        type: boolean
      registry:
        description: The registry to publish to, either `npm` or `github`
        required: true
        type: string
    secrets:
      NPM_AUTH_TOKEN:
        description: The token to authenticate with the NPM registry
        required: false

concurrency:
  group: ${{ github.workflow }}|${{ github.head_ref || github.ref }}|${{ inputs.working-directory }}|${{ inputs.registry }}|${{ inputs.operating-system }}|${{ inputs.bun-version }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish ${{ inputs.project-name }}
    runs-on: ${{ inputs.operating-system }}
    if: github.repository_owner == 'zendrex'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: ${{ inputs.with-submodules }}

      - name: Install Dependencies
        uses: zendrex/zendrex/.github/actions/install-bun-dependencies@main
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git"
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: zendrex+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Package Registries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          REGISTRY: ${{ inputs.registry }}
        run: |
          if [ "${REGISTRY}" = "npm" ]; then
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
          fi
          if [ "${REGISTRY}" = "github" ]; then
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          fi

      - name: Build
        if: inputs.build
        run: yarn build
      - name: Bump Versions and make release
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ "${{ inputs.skip-automatic-bump }}" = "true" ]; then
            bun x bump --skip-automatic-bump
          else
            bun x bump
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM Registry
        if: ${{ inputs.registry == 'npm' }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          bun x npm publish --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish to GitHub Registry
        if: ${{ inputs.registry == 'github' }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          bun x npm publish --registry https://npm.pkg.github.com/${{ github.repository_owner }}
