name: publish github

on:
  workflow_call:
    inputs:
      pr-number:
        description: The number of the PR that is being deployed
        required: false
        type: string
      ref:
        description: The branch that is being deployed. Should be a branch on the given repository
        required: false
        default: main
        type: string
      repository:
        description: The {owner}/{repository} that is being deployed.
        required: true
        type: string
      bun-version:
        description: The version of Bun to use (default `latest`)
        required: false
        default: latest
        type: string
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      with-submodules:
        description: Whether to include submodules when checking out the repository (default `false`)
        required: false
        default: 'false'
        type: string
      working-directory:
        description: The working directory to run the commands in
        required: false
        default: .
        type: string
      build:
        description: Whether to run `bun build` before publishing
        required: false
        default: false
        type: boolean
      registry:
        description: The registry to publish to, either `npm` or `github`
        required: true
        type: string
    secrets:
      NPM_AUTH_TOKEN:
        description: The token to authenticate with the NPM registry
        required: false

concurrency:
  group: ${{ github.workflow }}|${{ github.head_ref || github.ref }}|${{ inputs.working-directory }}|${{ inputs.registry }}|${{ inputs.operating-system }}|${{ inputs.repository }}|${{ inputs.bun-version }}
  cancel-in-progress: true

jobs:
  publish:
    name: Continuous Delivery
    runs-on: ${{ inputs.operating-system }}
    if: ${{ github.repository_owner == 'zendrex' }}
    env:
      TAG: ${{ github.event_name == 'push' && 'next' || format('pr-{0}', inputs['pr-number']) }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: ${{ inputs.with-submodules }}

      - name: Install Dependencies
        uses: zendrex/zendrex/.github/actions/install-bun-dependencies@main
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: Build
        if: ${{ inputs.build }}
        run: bun build

      - name: Configure Package Registries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          REGISTRY: ${{ inputs.registry }}
        run: |
          if [ "${REGISTRY}" = "npm" ]; then
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
          fi
          if [ "${REGISTRY}" = "github" ]; then
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          fi

      - name: Bump Version
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun run bump --preid "${TAG}.$(git rev-parse --short HEAD)" --skip-changelog

      - name: Publish to NPM Registry
        if: ${{ inputs.registry == 'npm' }}
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun x npm publish --tag ${TAG} --registry https://registry.npmjs.org/

      - name: Publish to GitHub Registry
        if: ${{ inputs.registry == 'github' }}
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun x npm publish --tag {TAG} --registry https://npm.pkg.github.com/${{ github.repository_owner }}
